---
# - debug:
#     msg: "Dist: {{ ansible_distribution }} Major: {{ ansible_distribution_major_version }}"

# Variable configuration.

- name: Load OS-specific vars.
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - '{{ansible_distribution}}.yml'
        - '{{ansible_os_family}}.yml'
        - main.yml
      paths:
        - 'vars'

# Custom Debian Setup

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

# Installation
