---

# - debug:
#     msg: "Dist: {{ ansible_distribution }} Major: {{ ansible_distribution_major_version }}"
#   tags: ['apache']


# Variable setup.
- name: Include OS-specific variables.
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "main.yml"
  ignore_errors: yes

